import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  safeArea: {
    // flex: 1,
    backgroundColor: "#000000ff",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "black",
  },
  content: {
    paddingBottom: 100,
  },
  backButton: {
    padding: 6,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFD700",
    textAlign: "center",
  },
  introContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
    paddingVertical: 10,
  },
  logoContainer: {
    marginTop: 20,
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  logoText: {
    color: "#FFD700",
    fontSize: 40,
    fontWeight: "bold",
  },
  logo: {
    width: 45,
    height: 45,
    marginHorizontal: 0,
  },
  versionText: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 20,
    marginBottom: 20,
  },
  introTitle: {
    padding: 5,
    fontWeight: "bold",
    fontSize: 50,
    marginTop: 10,
    textAlign: "center",
  },
  summarySection: {
    backgroundColor: "#ffffff",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  summaryImage: {
    width: 300,
    height: 225,
    borderRadius: 30,
    marginVertical: 20,
  },
  purposeSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fece00",
  },
  purposeImage: {
    marginVertical: 20,
    width: 300,
    height: 225,
    borderRadius: 20,
  },
  summaryTitle: {
    marginTop: 22,
    fontWeight: "bold",
    fontSize: 25,
  },
  summary: {
    textAlign: "justify",
    fontWeight: "300",
    fontSize: 16,
    paddingHorizontal: 35,
    paddingVertical: 10,
    marginBottom: 20,
  },
  outerTeamSection: {
    backgroundColor: "#ffffff",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  teamSection: {
    width: "85%",
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
    marginVertical: 30,
    paddingHorizontal: 25,
    paddingVertical: 20,
    borderWidth: 2,
    borderRadius: 15,
    borderColor: "#000",
    backgroundColor: "#ffffff",
  },
  teamTitle: {
    fontSize: 26,
    fontWeight: "bold",
  },
  memberImage: {
    width: 90,
    height: 90,
    borderRadius: 20,
    marginRight: 12,
  },
  teamMember: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "100%",
    alignItems: "center",
    marginHorizontal: 10,
    marginVertical: 15,
  },
  memberName: {
    fontWeight: "bold",
    fontSize: 20,
    marginBottom: 5,
  },
  memberRole: {
    fontSize: 17,
  },
  outerContactSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  contactSection: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "85%",
    borderWidth: 2,
    borderRadius: 15,
    borderColor: "#000",
    padding: 20,
    marginVertical: 30,
    paddingHorizontal: 25,
    paddingVertical: 20,
  },
  emailWithText: {
    flex: 1,
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 10,
  },
  contactTitle: {
    fontWeight: "bold",
    fontSize: 26,
  },
  email: {
    fontSize: 17,
    color: "#007AFF",
    textDecorationLine: "underline",
  },
  footerText: {
    textAlign: "center",
    fontSize: 16,
  },
});
