import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  safeArea: {
    // flex: 1,
    backgroundColor: "#000000ff",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    backgroundColor: "black",
    borderBottomColor: "#eee",
  },
  backButton: {
    padding: 6,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFD700",
    textAlign: "center",
  },
  content: {
    paddingHorizontal: 25,
    paddingTop: 20,
    paddingBottom: 100,
  },
  contentHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
    backgroundColor: "#000000ff",
    padding: 20,
    borderRadius: 16,
  },
  contentTitle: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "700",
    marginLeft: 15,
    color: "#ffffffff",
  },
  intro: {
    fontSize: 15,
    color: "#555",
    marginVertical: 20,
    lineHeight: 22,
    textAlign: "justify",
  },
  stepCard: {
    flexDirection: "row",
    backgroundColor: "#F9F9F9",
    borderRadius: 12,
    padding: 15,
    marginVertical: 15,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    borderWidth: 1.5,
  },
  icon: {
    width: 45,
    height: 40,
    backgroundColor: "#000",
    borderRadius: 15,
    paddingVertical: 5,
    paddingHorizontal: 7,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    marginTop: 4,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 4,
  },
  stepText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
    marginTop: 8,
    textAlign: "justify",
  },
  bold: {
    fontWeight: "bold",
  },
  mode: {
    fontSize: 14,
    color: "#444",
    marginTop: 2,
  },
  tip: {
    marginTop: 15,
    fontSize: 13,
    fontWeight: "bold",
    color: "#388E3C",
  },
  footer: {
    alignItems: "center",
  },
  doneTitle: {
    fontSize: 25,
    fontWeight: "700",
    color: "#2E7D32",
    marginTop: 6,
  },
  doneText: {
    fontSize: 14,
    color: "#555",
    marginTop: 4,
    textAlign: "center",
  },
  helpCard: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    borderRadius: 10,
    padding: 12,
    marginTop: 16,
    marginBottom: 30,
  },
  helpContainer: {
    flexDirection: "column",
    padding: 5,
  },
  helpText: {
    textAlign: "left",
    fontWeight: "bold",
    marginLeft: 10,
    fontSize: 14,
    color: "#2E7D32",
  },
  helpEmail: {
    marginLeft: 10,
  },
  boldEmail: {
    fontWeight: "bold",
  },
});
